#!/usr/bin/env bash
# Behavioral regressions for ask-user authority instructions generated by fm-brief.
set -u

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

BRIEF="$ROOT/bin/fm-brief.sh"
TMP_ROOT=$(fm_test_tmproot fm-ask-user-authority)

test_primary_and_secondmate_instruction_generation() {
  local home ship charter
  home="$TMP_ROOT/home"
  mkdir -p "$home/data"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" \
    "$BRIEF" authority-worker sample --mode no-mistakes >/dev/null 2>&1
  ship="$home/data/authority-worker/brief.md"
  assert_grep 'ask-user findings are never yours to answer' "$ship" \
    "generated implementation brief lets the worker own an ask-user decision"
  assert_grep "Firstmate applies \`ask-user-authority\` and obtains any required captain decision" "$ship" \
    "generated implementation brief bypasses the primary authority owner"
  assert_grep "silently bypass firstmate's authority check and any required captain escalation" "$ship" \
    "generated implementation brief permits silent ask-user auto-resolution"
  assert_no_grep 'the captain, not you, owns the ask-user decisions' "$ship" \
    "generated implementation brief retained conflicting captain-only wording"

  FM_HOME="$home" FM_ROOT_OVERRIDE="$ROOT" FM_SECONDMATE_CHARTER='Handle sample work.' \
    "$BRIEF" authority-mate --secondmate --no-projects >/dev/null 2>&1
  charter="$home/data/authority-mate/brief.md"
  # shellcheck disable=SC2016 # Backticks are literal generated Markdown.
  assert_grep 'The local `AGENTS.md` is your job description' "$charter" \
    "generated secondmate charter does not load the tracked authority boundary"
  assert_no_grep 'continuous frame-by-frame monitoring' "$charter" \
    "generated secondmate charter duplicated the detailed authority procedure"
  pass "primary workers and secondmates receive the authority rule through generated instructions"
}

test_primary_and_secondmate_instruction_generation

# The supervision branch previously declared EVERY ask-user finding captain-owned,
# so routine in-scope findings were reflexively escalated instead of decided. These
# assert the emitted branch prompt - the actual generated interface the branch agent
# receives - carries the corrected contract.
test_branch_prompt_finding_authority() {
  local prompt
  prompt="$TMP_ROOT/branch-prompt.txt"
  "$ROOT/bin/fm-branch-prompt.sh" > "$prompt"

  # 1. A routine in-scope finding is decided by firstmate and steered through the
  #    existing keyed gate, not turned into a captain-facing outcome.
  assert_grep 'send the worker the exact decision through the existing keyed gate rather than reporting verdict captain' "$prompt" \
    "emitted branch prompt does not tell the branch to decide a routine finding itself"
  assert_grep 'load that skill before deciding any finding' "$prompt" \
    "emitted branch prompt does not require loading the canonical authority skill"
  assert_no_grep 'including every ask-user finding from a validation gate' "$prompt" \
    "emitted branch prompt still declares every ask-user finding captain-owned"

  # 2. Round count, risk rating, the reviewer label, implementation conflict, and a
  #    recurring theme are each explicitly insufficient to escalate on their own.
  assert_grep 'a rising round count' "$prompt" \
    "emitted branch prompt does not rule out escalating on round count alone"
  assert_grep 'recurring theme are none of them reasons to escalate on their own' "$prompt" \
    "emitted branch prompt does not rule out escalating on a recurring theme alone"

  # 3. The stronger boundaries survive: genuine expansion and security ambiguity,
  #    merge, and destructive choices still reach the captain.
  assert_grep 'anything destructive, irreversible, or security-sensitive' "$prompt" \
    "emitted branch prompt lost the destructive/security captain boundary"
  assert_grep 'merge a PR, approve a validation step, or exercise any captain authority' "$prompt" \
    "emitted branch prompt lost the merge and captain-authority prohibition"
  assert_grep 'You still never answer the gate yourself' "$prompt" \
    "emitted branch prompt lets the branch answer the validation gate directly"

  pass "the emitted branch prompt decides routine findings and still escalates genuine captain calls"
}

test_branch_prompt_finding_authority
