#!/usr/bin/env bash
# Behavior tests for the isolated phynd-dev lifecycle and repo-owned tools.
set -u

# shellcheck source=tests/lib.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ROOT=${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}
TMP_ROOT=$(fm_test_tmproot phynd-dev-tests)
REAL_PATH=$PATH

make_fake_phynd_tools() {
  local dir=$1 tool
  mkdir -p "$dir"
  cat > "$dir/nix" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'nix (fake phynd-dev test)'
  exit 0
fi
if [ "${1:-}" = flake ] && [ "${2:-}" = update ]; then
  printf '%s\n' 'flake update' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
if [ "${1:-}" = flake ] && [ "${2:-}" = check ]; then
  printf '%s\n' 'flake check' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
if [ "${1:-}" = eval ]; then
  printf '%s\n' 'darwin configuration eval' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
exit 0
SH
  cat > "$dir/darwin-rebuild" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_REBUILD_LOG:?}"
mkdir -p "$PHYN_DEV_HOME/.local/bin"
mkdir -p "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager"
mkdir -p "$PHYN_DEV_HOME/.config/zsh"
printf '%s\n' '# generated by the fake Home Manager activation' \
  > "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/zshrc"
ln -sfn "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/zshrc" \
  "$PHYN_DEV_HOME/.config/zsh/.zshrc"
ln -sfn "$PHYN_DEV_ROOT/bin/phynd-dev" \
  "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/phynd-dev"
ln -sfn "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/phynd-dev" \
  "$PHYN_DEV_HOME/.local/bin/phynd-dev"
SH
  chmod +x "$dir/nix" "$dir/darwin-rebuild"
  cat > "$dir/brew" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = list ] && [ "${PHYN_TEST_MISSING_BREW_PACKAGE:-}" = "${3:-}" ]; then
  exit 1
fi
exit 0
SH
  chmod +x "$dir/brew"
  for tool in actionlint basedpyright basedpyright-langserver fd fresh fzf gh git jq \
    lua-language-server node npm npx rg rust-analyzer shellcheck starship treehouse \
    typescript-language-server tmux curl; do
    cat > "$dir/$tool" <<'SH'
#!/usr/bin/env bash
printf '%s\n' '❯'
SH
    chmod +x "$dir/$tool"
  done
  PHYN_TEST_NIX_PROFILE=$dir
  PHYN_TEST_SYSTEM_PROFILE=$dir
  PHYN_TEST_GLOBALBIN=
  PHYN_TEST_SKIP_TOOLS=1
  export PHYN_TEST_NIX_PROFILE PHYN_TEST_SYSTEM_PROFILE PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS
}

make_phynd_fixture() {
  local source=$1 fixture=$2
  mkdir -p "$fixture/bin" "$fixture/config/fresh" "$fixture/home/wezterm" "$fixture/nix"
  cp "$source/phynd-dev" "$fixture/phynd-dev"
  cp "$source/bin/phynd-dev" "$fixture/bin/phynd-dev"
  cp "$source/flake.nix" "$fixture/flake.nix"
  cp "$source/flake.lock" "$fixture/flake.lock" 2>/dev/null || : > "$fixture/flake.lock"
  cp "$source/config/fresh/config.json" "$fixture/config/fresh/config.json"
  cp "$source/config/starship.toml" "$fixture/config/starship.toml"
  cp "$source/home/wezterm/wezterm.lua" "$fixture/home/wezterm/wezterm.lua"
  cp "$source/nix/configuration.nix" "$fixture/nix/configuration.nix"
  cp "$source/nix/home.nix" "$fixture/nix/home.nix"
  chmod +x "$fixture/phynd-dev" "$fixture/bin/phynd-dev"
}

phynd_env() {
  local home=$1 xdg=$2 state=$3 npm_prefix=$4 log=$5 rebuild_log=$6 path
  shift 6
  path="$PHYN_TEST_FAKEBIN:$REAL_PATH"
  if [ -n "${PHYN_TEST_GLOBALBIN:-}" ]; then
    path="$PHYN_TEST_FAKEBIN:$PHYN_TEST_GLOBALBIN:$REAL_PATH"
  fi
  HOME="$home" \
  PHYN_DEV_HOME="$home" \
  PHYN_DEV_XDG_CONFIG_HOME="$xdg" \
  PHYN_DEV_STATE_DIR="$state" \
  PHYN_DEV_NPM_PREFIX="$npm_prefix" \
  PHYN_DEV_USER="$(id -un)" \
  PHYN_DEV_SKIP_SUDO=1 \
  PHYN_DEV_SKIP_TOOLS="${PHYN_TEST_SKIP_TOOLS:-1}" \
  PHYN_DEV_UNAME_S=Darwin \
  PHYN_DEV_UNAME_M=arm64 \
  PHYN_DEV_NIX_LOG="$log" \
  PHYN_DEV_REBUILD_LOG="$rebuild_log" \
  PHYN_DEV_NIX_PROFILE="${PHYN_TEST_NIX_PROFILE:-$home/nix-profile/bin}" \
  PHYN_DEV_SYSTEM_PROFILE="${PHYN_TEST_SYSTEM_PROFILE:-/run/current-system/sw/bin}" \
  PHYN_DEV_HM_PROFILE_ROOT="$home/.local/state/phynd-dev/home-manager" \
  PHYN_DEV_NIX_CUSTOM_CONF="${PHYN_DEV_NIX_CUSTOM_CONF:-$state/nix.custom.conf}" \
  PATH="$path" \
  "$@"
}

test_npm_tools_ignore_stale_path_commands() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log npm_log out count
  case_dir="$TMP_ROOT/npm-tools"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/custom-xdg"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  npm_log="$case_dir/npm.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  cat > "$case_dir/fakebin/npm" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_NPM_LOG:?}"
mkdir -p "$NPM_CONFIG_PREFIX/bin"
for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
  cat > "$NPM_CONFIG_PREFIX/bin/$tool" <<'TOOL'
#!/usr/bin/env bash
exit 0
TOOL
  chmod +x "$NPM_CONFIG_PREFIX/bin/$tool"
done
SH
  chmod +x "$case_dir/fakebin/npm"
  mkdir -p "$case_dir/globalbin"
  cat > "$case_dir/globalbin/no-mistakes" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'no-mistakes version v1.46.0 (fake)'
fi
SH
  chmod +x "$case_dir/globalbin/no-mistakes"
  for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
    cat > "$case_dir/globalbin/$tool" <<'SH'
#!/usr/bin/env bash
exit 0
SH
    chmod +x "$case_dir/globalbin/$tool"
  done
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  PHYN_TEST_SKIP_TOOLS=0
  PHYN_DEV_BACKUP_SUFFIX=ghf-test
  PHYN_DEV_NPM_LOG="$npm_log"
  export PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS PHYN_DEV_BACKUP_SUFFIX PHYN_DEV_NPM_LOG
  : > "$nix_log"
  : > "$rebuild_log"
  : > "$npm_log"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "npm-tool reconciliation failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 7 ] || fail "initial install should reconcile each npm tool once"
  rm "$home/.local/bin/ghf"
  printf '%s\n' unrelated > "$home/.local/bin/ghf"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "ghf backup repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 14 ] || fail "an unrelated ghf target should trigger gnhf repair"
  [ "$(cat "$home/.local/bin/ghf.phynd-dev-backup-ghf-test")" = unrelated ] \
    || fail "an unrelated ghf target should be preserved in a backup"
  [ -L "$home/.local/bin/ghf" ] || fail "gnhf repair should restore the managed ghf link"
  rm -f "$home/.local/bin/ghf"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "ghf-link repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 21 ] || fail "missing ghf link should trigger gnhf repair"
  rm "$npm_prefix/bin/"*
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "npm-tool repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 28 ] || fail "stale global npm tools should not suppress repair"
  pass "npm-managed tools ignore stale commands outside the managed prefix"
}

test_root_entrypoint_resolves_itself() {
  local case_dir out
  case_dir="$TMP_ROOT/root-entrypoint"
  mkdir -p "$case_dir/home"
  out=$(cd /tmp && HOME="$case_dir/home" PHYN_DEV_UNAME_S=Darwin \
    PHYN_DEV_UNAME_M=arm64 "$ROOT/phynd-dev" status) \
    || fail "root phynd-dev entrypoint should work from another caller directory"
  assert_contains "$out" "checkout: $ROOT" "root entrypoint should identify its own checkout"
  assert_contains "$out" "system:   aarch64-darwin" "root entrypoint should resolve the host system"
  pass "root phynd-dev delegates to bin/phynd-dev independent of caller directory"
}

test_install_tool_repairs_outdated_no_mistakes() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log marker out
  case_dir="$TMP_ROOT/no-mistakes-repair"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  marker="$case_dir/repaired"
  mkdir -p "$home" "$case_dir/globalbin"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  PHYN_TEST_SKIP_TOOLS=1
  PHYN_DEV_NM_MARKER="$marker"
  export PHYN_TEST_FAKEBIN PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS PHYN_DEV_NM_MARKER
  cat > "$case_dir/globalbin/no-mistakes" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'no-mistakes version v1.45.4 (fake)'
fi
SH
  chmod +x "$case_dir/globalbin/no-mistakes"
  cat > "$case_dir/fakebin/curl" <<'SH'
#!/usr/bin/env bash
printf '%s\n' 'printf repaired > "${PHYN_DEV_NM_MARKER:?}"'
SH
  chmod +x "$case_dir/fakebin/curl"
  cat > "$case_dir/fakebin/npm" <<'SH'
#!/usr/bin/env bash
mkdir -p "$NPM_CONFIG_PREFIX/bin"
for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
  printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$NPM_CONFIG_PREFIX/bin/$tool"
  chmod +x "$NPM_CONFIG_PREFIX/bin/$tool"
done
SH
  chmod +x "$case_dir/fakebin/npm"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install-tool no-mistakes) \
    || fail "outdated no-mistakes repair failed: $out"
  [ "$(cat "$marker")" = repaired ] \
    || fail "outdated no-mistakes should run the official installer"
  rm "$marker"
  PHYN_TEST_SKIP_TOOLS=0
  export PHYN_TEST_SKIP_TOOLS
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) \
    || fail "regular install should repair outdated no-mistakes: $out"
  [ "$(cat "$marker")" = repaired ] \
    || fail "regular install should use the no-mistakes version convergence check"
  pass "phynd-dev repairs outdated no-mistakes installations"
}

test_install_noop_update_and_safe_backup() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log system_profile out count
  case_dir="$TMP_ROOT/lifecycle"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/custom-xdg"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home" "$xdg/fresh"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  export PHYN_DEV_BACKUP_SUFFIX=test
  : > "$nix_log"
  : > "$rebuild_log"
  printf '%s\n' '{"captain_private":true}' > "$xdg/fresh/config.json"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "initial phynd-dev install failed: $out"
  assert_contains "$out" "activation state recorded" "initial install should record activation"
  [ -L "$xdg/fresh/config.json" ] || fail "Fresh config should be linked after install"
  [ "$(readlink "$xdg/fresh/config.json")" = "$fixture/config/fresh/config.json" ] \
    || fail "Fresh link should target the repository source"
  [ "$(cat "$xdg/fresh/config.json.phynd-dev-backup-test")" = '{"captain_private":true}' ] \
    || fail "existing Fresh configuration should be preserved in a backup"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 1 ] || fail "initial install should activate exactly once"

  out=$(cd /tmp && HOME="$home" PHYN_DEV_HOME="$home" \
    PHYN_DEV_UNAME_S=Darwin PHYN_DEV_UNAME_M=arm64 \
    "$home/.local/bin/phynd-dev" status) \
    || fail "the Home Manager-installed phynd-dev command failed: $out"
  assert_contains "$out" "checkout: $fixture" \
    "the installed phynd-dev command should resolve its repository root"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "second phynd-dev install failed: $out"
  assert_contains "$out" "already converged" "second install should report a no-op"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 1 ] || fail "second install should not reactivate nix-darwin"

  rm "$home/.config/zsh/.zshrc"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Home Manager shell state: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 2 ] || fail "missing Home Manager shell state should trigger activation"

  PHYN_TEST_MISSING_BREW_PACKAGE=herdr
  export PHYN_TEST_MISSING_BREW_PACKAGE
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Homebrew formula state: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 3 ] || fail "missing Homebrew formula should trigger activation"
  unset PHYN_TEST_MISSING_BREW_PACKAGE

  system_profile="$case_dir/system-profile"
  mkdir -p "$system_profile"
  cp "$case_dir/fakebin/fresh" "$system_profile/fresh"
  PHYN_TEST_SYSTEM_PROFILE="$system_profile"
  export PHYN_TEST_SYSTEM_PROFILE
  rm "$case_dir/fakebin/fresh"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair a Home Manager package shadowed by system PATH: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 4 ] || fail "a stale system package should not suppress Home Manager repair"
  cp "$system_profile/fresh" "$case_dir/fakebin/fresh"
  chmod +x "$case_dir/fakebin/fresh"

  mkdir -p "$case_dir/globalbin"
  cp "$case_dir/fakebin/starship" "$case_dir/globalbin/starship"
  chmod +x "$case_dir/globalbin/starship"
  rm "$case_dir/fakebin/starship"
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  export PHYN_TEST_GLOBALBIN
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Nix-managed packages: $out"
  assert_contains "$out" "applying pinned nix-darwin" \
    "a missing managed package should invalidate the activation no-op"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 5 ] || fail "missing managed package should trigger one reactivation"
  cat > "$case_dir/fakebin/starship" <<'SH'
#!/usr/bin/env bash
printf '%s\n' '❯'
SH
  chmod +x "$case_dir/fakebin/starship"

  printf '\n# later repo configuration revision\n' >> "$fixture/config/starship.toml"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" update) \
    || fail "phynd-dev update failed: $out"
  assert_contains "$out" "applying pinned nix-darwin" "changed configuration should reactivate"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 6 ] || fail "updated configuration should activate once more"
  pass "phynd-dev install, converged no-op, update, and safe backup paths are idempotent"
}

test_activation_handles_determinate_custom_conf() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log conf backup out expected
  case_dir="$TMP_ROOT/nix-custom-conf"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  conf="$case_dir/etc/nix/nix.custom.conf"
  backup="$conf.before-nix-darwin"
  mkdir -p "$home" "$case_dir/etc/nix"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  PHYN_DEV_NIX_CUSTOM_CONF="$conf"
  export PHYN_TEST_FAKEBIN PHYN_DEV_NIX_CUSTOM_CONF
  : > "$nix_log"
  : > "$rebuild_log"
  {
    printf '%s\n' \
      '# Written by https://github.com/DeterminateSystems/nix-installer.' \
      '# The contents below are based on options specified at installation time.'
    printf '\n'
  } > "$conf"
  expected=$(printf '%s\n%s' \
    '# Written by https://github.com/DeterminateSystems/nix-installer.' \
    '# The contents below are based on options specified at installation time.')

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "installer-owned Nix config should be preserved: $out"
  [ ! -e "$conf" ] || fail "installer-owned Nix config should be moved before activation"
  [ "$(cat "$backup")" = "$expected" ] \
    || fail "installer-owned Nix config should be retained byte-for-byte"
  assert_contains "$out" "preserved the Determinate installer Nix config" \
    "activation should report the preserved installer config"

  printf '%s\n' 'experimental-features = nix-command flakes' > "$conf"
  printf '\n# force a second activation\n' >> "$fixture/config/starship.toml"
  if out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install 2>&1); then
    fail "activation should reject an unrecognized Nix config"
  fi
  [ -f "$conf" ] || fail "an unrecognized Nix config should not be moved"
  assert_contains "$out" "unmanaged Nix config" \
    "activation should explain how to handle an unrecognized Nix config"
  pass "activation safely prepares the Determinate installer Nix config"

  unset PHYN_DEV_NIX_CUSTOM_CONF
}

test_flake_update_and_check_are_explicit() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log out
  case_dir="$TMP_ROOT/flake-actions"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  : > "$nix_log"
  : > "$rebuild_log"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" flake-check) || fail "flake-check path failed: $out"
  assert_contains "$out" "evaluating the pinned flake" "flake-check should explain its action"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" flake-update) || fail "flake-update path failed: $out"
  assert_contains "$out" "updating the flake lock" "flake-update should explain its action"
  assert_contains "$(cat "$nix_log")" "flake check" "flake-check should invoke nix"
  assert_contains "$(cat "$nix_log")" "darwin configuration eval" \
    "flake-check should evaluate the Darwin configuration"
  assert_contains "$(cat "$nix_log")" "flake update" "flake-update should invoke nix"
  if [ "$(uname -s)" = Darwin ] && PATH="$REAL_PATH" command -v nix >/dev/null 2>&1; then
    out=$(PATH="$REAL_PATH" nix flake check --no-build --impure "$fixture") \
      || fail "real Nix could not evaluate the pinned fixture flake: $out"
    out=$(PATH="$REAL_PATH" nix eval --no-write-lock-file --impure --raw \
      "$fixture#darwinConfigurations.phynd-dev.config.system.build.toplevel.drvPath") \
      || fail "real Nix could not evaluate the Darwin/Home Manager configuration: $out"
    pass "real Nix evaluates the flake and Darwin configuration without building closures"
  else
    pass "real Nix evaluation skipped because this host lacks Darwin Nix"
  fi
  pass "flake-check and flake-update remain explicit, separate lifecycle paths"
}

test_fresh_effective_config_and_wezterm_load() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log show out lsp_path
  case_dir="$TMP_ROOT/editor-config"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  : > "$nix_log"
  : > "$rebuild_log"
  phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install >/dev/null \
    || fail "editor-config install failed"

  if [ "$(uname -s)" = Darwin ]; then
    command -v fresh >/dev/null 2>&1 \
      || fail "Fresh is required on the supported Darwin path"
    show=$(HOME="$home" XDG_CONFIG_HOME="$xdg" PATH="$REAL_PATH" \
      fresh --cmd config show) || fail "Fresh could not load the activated repo config"
    printf '%s\n' "$show" | jq -e '
      .file_explorer.show_gitignored == true and
      .file_explorer.respect_gitignore == true and
      .lsp.typescript[0].command == "typescript-language-server" and
      .lsp.typescript[0].auto_start == true and
      .lsp.javascript[0].command == "typescript-language-server" and
      .lsp.rust[0].command == "rust-analyzer" and
      .lsp.lua[0].command == "lua-language-server" and
      .lsp.python[0].command == "basedpyright-langserver" and
      (.lsp.typescript[0].root_markers | index(".git")) != null and
      (.lsp.rust[0].root_markers | index("Cargo.toml")) != null and
      (.lsp.python[0].root_markers | index("pyproject.toml")) != null
    ' >/dev/null || fail "Fresh effective config did not expose the managed explorer and LSP settings"
    lsp_path="$case_dir/lsp-bin"
    mkdir -p "$lsp_path"
    for tool in typescript-language-server rust-analyzer lua-language-server basedpyright-langserver; do
      cat > "$lsp_path/$tool" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$(basename "$0")" >> "${FRESH_LSP_LOG:?}"
while IFS= read -r line; do
  :
done
SH
      chmod +x "$lsp_path/$tool"
    done
    # Fresh 0.3.1 does not deterministically auto-start Lua for daemon open-file;
    # the effective-config assertion above remains the stable Lua contract.
    for language in typescript javascript rust python; do
      workspace="$case_dir/workspace/apps/$language/src"
      mkdir -p "$workspace"
      case "$language" in
        typescript) file="$workspace/main.ts" ;;
        javascript) file="$workspace/main.js" ;;
        rust) file="$workspace/main.rs" ;;
        lua) file="$workspace/main.lua" ;;
        python) file="$workspace/main.py" ;;
      esac
      printf '%s\n' invalid > "$file"
      session="phynd-$language"
      lsp_log="$case_dir/$language-lsp.log"
      : > "$lsp_log"
      out=$(HOME="$home" XDG_CONFIG_HOME="$xdg" \
        FRESH_LSP_LOG="$lsp_log" \
        PATH="$lsp_path:$REAL_PATH" \
        fresh --no-upgrade-check --cmd daemon open-file "$session" "$file" 2>&1) \
        || fail "Fresh could not attach the isolated $language workspace: $out"
      printf '%s\n' "$out" | grep -Fqi "opened 1 file(s)" \
        || fail "Fresh should attach the isolated $language workspace through its daemon: $out"
      attempts=0
      while [ ! -s "$lsp_log" ] && [ "$attempts" -lt 50 ]; do
        sleep 0.1
        attempts=$((attempts + 1))
      done
      [ -s "$lsp_log" ] \
        || fail "Fresh did not start the configured $language language server"
      HOME="$home" XDG_CONFIG_HOME="$xdg" \
        PATH="$lsp_path:$REAL_PATH" \
        fresh --no-upgrade-check --cmd daemon kill "$session" >/dev/null 2>&1 || :
    done
    pass "Fresh loads managed settings and starts the four deterministic language servers"
  else
    pass "Fresh executable validation skipped outside the supported Darwin host"
  fi

  if command -v wezterm >/dev/null 2>&1; then
    out=$(HOME="$home" XDG_CONFIG_HOME="$xdg" PATH="$REAL_PATH" \
      wezterm show-keys --lua 2>&1) || fail "WezTerm could not load the activated repo Lua config: $out"
    pass "WezTerm's config-loading surface accepts the activated repo-owned Lua source"
  else
    pass "WezTerm config-loading validation skipped because WezTerm is not installed in this test environment"
  fi
}

test_repo_starship_config_is_usable() {
  local out
  if command -v starship >/dev/null 2>&1; then
    out=$(STARSHIP_CONFIG="$ROOT/config/starship.toml" starship prompt 2>&1) \
      || fail "Starship could not render the repo-owned configuration: $out"
    [ -n "$out" ] || fail "Starship rendered an empty prompt from the repo-owned configuration"
    pass "Starship renders a prompt from the repo-owned configuration"
  else
    pass "Starship prompt validation skipped because Starship is not installed in this test environment"
  fi
}

test_starship_is_nix_managed_and_loaded_once() {
  local shell_home zsh_dir zshrc zshenv zprofile zlogin enabled out call_log
  local hm_session_vars autosuggestions syntax_highlighting
  if [ "$(uname -s)" != Darwin ] || ! command -v nix >/dev/null 2>&1 || \
    ! command -v zsh >/dev/null 2>&1; then
    pass "Starship Nix activation validation skipped outside a Darwin host with Nix"
    return 0
  fi
  shell_home="$TMP_ROOT/starship-shell-home"
  mkdir -p "$shell_home/bin"
  printf '%s\n' 'export PHYN_EXISTING_ENV=preserved' > "$shell_home/.zshenv"
  printf '%s\n' 'export PHYN_EXISTING_PROFILE=preserved' > "$shell_home/.zprofile"
  printf '%s\n' 'export PHYN_EXISTING_LOGIN=preserved' > "$shell_home/.zlogin"
  # shellcheck disable=SC2016 # The fixture must contain a literal command substitution.
  printf '%s\n' 'eval "$(starship init zsh)"' > "$shell_home/.zshrc"
  call_log="$shell_home/starship-calls.log"
  cat > "$shell_home/bin/starship" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = init ] && [ "${2:-}" = zsh ]; then
  printf '%s\n' init >> "${STARSHIP_CALL_LOG:?}"
  printf '%s\n' 'PROMPT="❯ "'
fi
SH
  chmod +x "$shell_home/bin/starship"
  enabled=$(nix eval --impure --json \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.programs.starship.enableZshIntegration") \
    || fail "Nix could not evaluate the generated Starship zsh integration setting"
  [ "$enabled" = true ] || fail "Home Manager should own Starship's zsh integration"
  zshrc=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zshrc\".text") \
    || fail "Nix could not evaluate the generated interactive zsh configuration"
  zshenv=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zshenv\".text") \
    || fail "Nix could not evaluate the generated zshenv configuration"
  zprofile=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zprofile\".text") \
    || fail "Nix could not evaluate the generated zprofile configuration"
  zlogin=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zlogin\".text") \
    || fail "Nix could not evaluate the generated zlogin configuration"
  hm_session_vars="$shell_home/hm-session-vars.sh"
  autosuggestions="$shell_home/zsh-autosuggestions.zsh"
  syntax_highlighting="$shell_home/zsh-syntax-highlighting.zsh"
  : > "$hm_session_vars"
  : > "$autosuggestions"
  : > "$syntax_highlighting"
  zshenv=$(printf '%s\n' "$zshenv" | sed -E \
    "s|/nix/store/[^\"]+-hm-session-vars\\.sh/etc/profile\\.d/hm-session-vars\\.sh|$hm_session_vars|g")
  zshrc=$(printf '%s\n' "$zshrc" | sed -E \
    -e "s|/nix/store/[^[:space:]]+-zsh-autosuggestions-[^[:space:]]+/share/zsh-autosuggestions/zsh-autosuggestions\\.zsh|$autosuggestions|g" \
    -e "s|/nix/store/[^[:space:]]+-starship-[^[:space:]]+/bin/starship|$shell_home/bin/starship|g" \
    -e "s|/nix/store/[^[:space:]]+-zsh-syntax-highlighting-[^[:space:]]+/share/zsh-syntax-highlighting/zsh-syntax-highlighting\\.zsh|$syntax_highlighting|g")
  zsh_dir="$shell_home/.config/zsh"
  mkdir -p "$zsh_dir"
  printf '%s\n' "$zshenv" > "$zsh_dir/.zshenv"
  printf '%s\n' "$zprofile" > "$zsh_dir/.zprofile"
  printf '%s\n' "$zshrc" > "$zsh_dir/.zshrc"
  printf '%s\n' "$zlogin" > "$zsh_dir/.zlogin"
  out=$(HOME="$shell_home" ZDOTDIR="$zsh_dir" TERM=xterm \
    STARSHIP_CALL_LOG="$call_log" PATH="$shell_home/bin:$PATH" \
    zsh -ilc 'printf "%s\\n" "$PHYN_EXISTING_ENV" "$PHYN_EXISTING_PROFILE" "$PHYN_EXISTING_LOGIN"; print -P -- "$PROMPT"' 2>&1) \
    || fail "a fresh interactive zsh could not load the generated configuration: $out"
  assert_contains "$out" "preserved" \
    "a fresh interactive zsh should preserve all conventional user startup files"
  assert_contains "$out" "❯" \
    "a fresh interactive zsh should render the repo-owned Starship prompt"
  [ "$(wc -l < "$call_log" | tr -d ' ')" -eq 1 ] \
    || fail "a fresh interactive zsh should initialize Starship exactly once"
  pass "Nix-managed Starship renders through the generated interactive zsh configuration"
}

# REAL_PATH still resolves this host's own real Nix (e.g. /nix/var/nix/profiles/
# default/bin and ~/.nix-profile/bin), which every "missing Nix" fixture below
# must not silently fall through to. NIX_FREE_PATH strips any such component so
# command -v nix genuinely fails until the fake installer "bootstraps" one.
NIX_FREE_PATH=$(printf '%s' "$REAL_PATH" | tr ':' '\n' | grep -v -i '/nix' | tr '\n' ':')
NIX_FREE_PATH=${NIX_FREE_PATH%:}

linux_phynd_env() {
  local home=$1 xdg=$2 state=$3 npm_prefix=$4 fakebin=$5 uname_m=$6 script=$7
  shift 7
  HOME="$home" \
  PHYN_DEV_HOME="$home" \
  PHYN_DEV_XDG_CONFIG_HOME="$xdg" \
  PHYN_DEV_STATE_DIR="$state" \
  PHYN_DEV_NPM_PREFIX="$npm_prefix" \
  PHYN_DEV_USER="$(id -un)" \
  PHYN_DEV_UNAME_S=Linux \
  PHYN_DEV_UNAME_M="$uname_m" \
  PHYN_DEV_NIX_PROFILE="$fakebin/hm-profile" \
  PHYN_DEV_SYSTEM_PROFILE="$fakebin/no-such-system-profile" \
  PATH="$fakebin:$REAL_PATH" \
  "$script" "$@"
}

# These exported test fixture variables persist for the rest of this bash
# process once any Linux install test sets them (export has no function
# scope), so a later test can otherwise silently inherit an earlier test's
# now-real fake-nix path or log file. Every Linux install test starts by
# clearing this exact set before exporting only what it itself needs.
unset_linux_install_test_env() {
  unset PHYN_DEV_NIX_BIN PHYN_DEV_HM_OUT PHYN_DEV_CURL_LOG PHYN_DEV_NIX_LOG \
    PHYN_DEV_HM_ACTIVATE_LOG PHYN_DEV_NIX_STUB_SRC PHYN_DEV_NIX_DAEMON_PROFILE \
    PHYN_DEV_NIX_DAEMON_PROFILE_SCRIPT PHYN_DEV_HM_PROFILE_ROOT PHYN_DEV_SKIP_TOOLS
}

# Same contract as linux_phynd_env, but with this host's own real Nix excluded
# from PATH: for fixtures that must observe a genuinely missing Nix. Also
# neutralizes the Darwin-only per-user/system profile path defaults (real
# nix-darwin paths on this host, e.g. /run/current-system/sw/bin's real curl)
# so refresh_path's prepend can never leak this host's real tools ahead of the
# fixture's own fakebin.
linux_phynd_env_no_ambient_nix() {
  local home=$1 xdg=$2 state=$3 npm_prefix=$4 fakebin=$5 uname_m=$6 script=$7
  shift 7
  HOME="$home" \
  PHYN_DEV_HOME="$home" \
  PHYN_DEV_XDG_CONFIG_HOME="$xdg" \
  PHYN_DEV_STATE_DIR="$state" \
  PHYN_DEV_NPM_PREFIX="$npm_prefix" \
  PHYN_DEV_USER="$(id -un)" \
  PHYN_DEV_UNAME_S=Linux \
  PHYN_DEV_UNAME_M="$uname_m" \
  PHYN_DEV_NIX_PROFILE="$fakebin/hm-profile" \
  PHYN_DEV_SYSTEM_PROFILE="$fakebin/no-such-system-profile" \
  PATH="$fakebin:$NIX_FREE_PATH" \
  "$script" "$@"
}

test_host_system_detects_linux_and_refuses_unsupported() {
  local case_dir out
  case_dir="$TMP_ROOT/host-system"
  mkdir -p "$case_dir/home-x86" "$case_dir/home-arm" "$case_dir/home-unsupported-os" \
    "$case_dir/home-unsupported-arch"

  out=$(HOME="$case_dir/home-x86" PHYN_DEV_UNAME_S=Linux PHYN_DEV_UNAME_M=x86_64 \
    "$ROOT/phynd-dev" status) || fail "x86_64 Linux dispatch failed: $out"
  assert_contains "$out" "system:   x86_64-linux" "x86_64 Linux should resolve to x86_64-linux"

  out=$(HOME="$case_dir/home-arm" PHYN_DEV_UNAME_S=Linux PHYN_DEV_UNAME_M=aarch64 \
    "$ROOT/phynd-dev" status) || fail "aarch64 Linux dispatch failed: $out"
  assert_contains "$out" "system:   aarch64-linux" "aarch64 Linux should resolve to aarch64-linux"

  if out=$(HOME="$case_dir/home-unsupported-os" PHYN_DEV_UNAME_S=FreeBSD PHYN_DEV_UNAME_M=x86_64 \
    "$ROOT/phynd-dev" status 2>&1); then
    fail "an unsupported OS should refuse instead of proceeding: $out"
  fi
  assert_contains "$out" "phynd-dev supports macOS" \
    "an unsupported OS should explain the supported platforms"
  [ ! -d "$case_dir/home-unsupported-os/.local/state/phynd-dev" ] \
    || fail "an unsupported OS should refuse before creating any state directory"

  if out=$(HOME="$case_dir/home-unsupported-arch" PHYN_DEV_UNAME_S=Linux PHYN_DEV_UNAME_M=mips64 \
    "$ROOT/phynd-dev" status 2>&1); then
    fail "an unsupported Linux architecture should refuse instead of proceeding: $out"
  fi
  assert_contains "$out" "Linux (aarch64 or x86_64)" \
    "an unsupported Linux architecture should name the supported architectures"
  pass "host_system detects Linux, resolves both architectures, and refuses unsupported OS/architecture before any side effect"
}

test_linux_install_bootstraps_nix_then_activates_home_manager() {
  unset_linux_install_test_env
  local case_dir fixture home xdg state npm_prefix fakebin out
  local nix_stub_src nix_bin hm_out curl_log nix_log activate_log
  case_dir="$TMP_ROOT/linux-bootstrap"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  fakebin="$case_dir/fakebin"
  nix_bin="$case_dir/bootstrapped-nix/bin/nix"
  hm_out="$case_dir/hm-generation"
  curl_log="$case_dir/curl.log"
  nix_log="$case_dir/nix-build.log"
  activate_log="$case_dir/activate.log"
  nix_stub_src="$case_dir/nix-stub"
  mkdir -p "$home" "$fakebin" "$hm_out"
  make_phynd_fixture "$ROOT" "$fixture"
  : > "$curl_log"
  : > "$nix_log"
  : > "$activate_log"

  # The fake nix binary the fake installer "installs": handles --version and
  # the Linux activation path's `nix build ...#homeConfigurations....`.
  cat > "$nix_stub_src" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'nix (fake bootstrapped Linux Nix)'
  exit 0
fi
if [ "${1:-}" = build ]; then
  printf '%s\n' "$*" >> "${PHYN_DEV_NIX_LOG:?}"
  printf '%s\n' "${PHYN_DEV_HM_OUT:?}"
  exit 0
fi
exit 0
SH
  chmod +x "$nix_stub_src"

  # The activation package's own generated script; the real flake output
  # would contain this, so the test pre-builds only its externally observable
  # contract (what it links/writes), not Nix's internal derivation machinery.
  cat > "$hm_out/activate" <<'SH'
#!/usr/bin/env bash
printf 'activated\n' >> "${PHYN_DEV_HM_ACTIVATE_LOG:?}"
# Writes into PHYN_DEV_NIX_PROFILE, not PHYN_DEV_HOME/.nix-profile: this host's
# own real /etc/profiles/per-user/<user>/bin already provides every one of
# these tool names for real (this repo's own home.nix, activated on the
# captain's machine), and refresh_path checks that real per-user path before
# DEV_HOME_MANAGER_PROFILE/bin, so a stub placed there would never be found
# first. PHYN_DEV_NIX_PROFILE is checked earlier and is fully test-owned.
# The real activation script's own generated files live under its own
# output tree (matching /nix/store/*-home-manager-files/* in production);
# PHYN_DEV_HM_PROFILE_ROOT points home_manager_file_converged at this fake
# stand-in for that tree instead of a real, unwritable /nix/store path.
mkdir -p "$PHYN_DEV_HOME/.config/zsh" "${PHYN_DEV_NIX_PROFILE:?}" "${PHYN_DEV_HM_PROFILE_ROOT:?}"
printf '%s\n' '# generated by the fake standalone Home Manager activation' \
  > "${PHYN_DEV_HM_PROFILE_ROOT:?}/zshrc"
ln -sfn "${PHYN_DEV_HM_PROFILE_ROOT:?}/zshrc" \
  "$PHYN_DEV_HOME/.config/zsh/.zshrc"
mkdir -p "$PHYN_DEV_HOME/.local/bin"
ln -sfn "${PHYN_DEV_ROOT:?}/bin/phynd-dev" "$PHYN_DEV_HOME/.local/bin/phynd-dev"
for tool in actionlint basedpyright basedpyright-langserver fd fresh fzf gh jq \
  lua-language-server node npm npx rg rust-analyzer shellcheck starship \
  treehouse typescript-language-server; do
  cat > "${PHYN_DEV_NIX_PROFILE:?}/$tool" <<'TOOL'
#!/usr/bin/env bash
printf '%s\n' '❯'
TOOL
  chmod +x "${PHYN_DEV_NIX_PROFILE:?}/$tool"
done
SH
  chmod +x "$hm_out/activate"

  cat > "$fakebin/curl" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_CURL_LOG:?}"
mkdir -p "$(dirname "${PHYN_DEV_NIX_BIN:?}")"
cp "${PHYN_DEV_NIX_STUB_SRC:?}" "${PHYN_DEV_NIX_BIN:?}"
chmod +x "${PHYN_DEV_NIX_BIN:?}"
SH
  chmod +x "$fakebin/curl"
  for tool in npm shasum; do
    command -v "$tool" >/dev/null 2>&1 || fail "test host is missing $tool, required by this fixture"
  done

  export PHYN_DEV_NIX_BIN="$nix_bin" PHYN_DEV_HM_OUT="$hm_out" \
    PHYN_DEV_CURL_LOG="$curl_log" PHYN_DEV_NIX_LOG="$nix_log" \
    PHYN_DEV_HM_ACTIVATE_LOG="$activate_log" PHYN_DEV_NIX_STUB_SRC="$nix_stub_src" \
    PHYN_DEV_NIX_DAEMON_PROFILE="$case_dir/no-such-daemon-nix" \
    PHYN_DEV_NIX_DAEMON_PROFILE_SCRIPT="$case_dir/no-such-daemon-nix.sh" \
    PHYN_DEV_HM_PROFILE_ROOT="$hm_out/home-files" \
    PHYN_DEV_SKIP_TOOLS=1

  out=$(linux_phynd_env_no_ambient_nix "$home" "$xdg" "$state" "$npm_prefix" "$fakebin" x86_64 \
    "$fixture/phynd-dev" install) || fail "Linux install with missing Nix failed: $out"
  assert_contains "$(cat "$curl_log")" "install.determinate.systems/nix" \
    "missing Nix on Linux should bootstrap through the Determinate installer"
  assert_contains "$(cat "$nix_log")" "#homeConfigurations.phynd-dev.activationPackage" \
    "Linux activation should build the flake's own standalone Home Manager output"
  [ -s "$activate_log" ] || fail "Linux activation should run the built activation script"
  [ -L "$home/.config/zsh/.zshrc" ] || fail "Linux activation should link the generated zshrc"

  : > "$curl_log"
  : > "$nix_log"
  : > "$activate_log"
  out=$(linux_phynd_env_no_ambient_nix "$home" "$xdg" "$state" "$npm_prefix" "$fakebin" x86_64 \
    "$fixture/phynd-dev" install) || fail "second Linux install failed: $out"
  assert_contains "$out" "already converged" "a converged Linux install should report a no-op"
  [ ! -s "$curl_log" ] || fail "a converged Linux install should not re-bootstrap Nix"
  [ ! -s "$nix_log" ] || fail "a converged Linux install should not rebuild the Home Manager profile"
  pass "phynd-dev bootstraps missing Nix and activates standalone Home Manager on Linux, then converges"
}

test_linux_existing_nix_is_reused_without_bootstrapping() {
  unset_linux_install_test_env
  local case_dir fixture home xdg state npm_prefix fakebin out
  local hm_out nix_log activate_log
  case_dir="$TMP_ROOT/linux-existing-nix"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  fakebin="$case_dir/fakebin"
  hm_out="$case_dir/hm-generation"
  nix_log="$case_dir/nix-build.log"
  activate_log="$case_dir/activate.log"
  mkdir -p "$home" "$fakebin" "$hm_out"
  make_phynd_fixture "$ROOT" "$fixture"
  : > "$nix_log"
  : > "$activate_log"

  cat > "$fakebin/nix" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'nix (fake pre-existing Linux Nix)'
  exit 0
fi
if [ "${1:-}" = build ]; then
  printf '%s\n' "$*" >> "${PHYN_DEV_NIX_LOG:?}"
  printf '%s\n' "${PHYN_DEV_HM_OUT:?}"
  exit 0
fi
exit 0
SH
  chmod +x "$fakebin/nix"
  cat > "$hm_out/activate" <<'SH'
#!/usr/bin/env bash
printf 'activated\n' >> "${PHYN_DEV_HM_ACTIVATE_LOG:?}"
mkdir -p "$PHYN_DEV_HOME/.config/zsh" "${PHYN_DEV_NIX_PROFILE:?}" "${PHYN_DEV_HM_PROFILE_ROOT:?}"
printf '%s\n' '# generated' > "${PHYN_DEV_HM_PROFILE_ROOT:?}/zshrc"
ln -sfn "${PHYN_DEV_HM_PROFILE_ROOT:?}/zshrc" \
  "$PHYN_DEV_HOME/.config/zsh/.zshrc"
mkdir -p "$PHYN_DEV_HOME/.local/bin"
ln -sfn "${PHYN_DEV_ROOT:?}/bin/phynd-dev" "$PHYN_DEV_HOME/.local/bin/phynd-dev"
for tool in actionlint basedpyright basedpyright-langserver fd fresh fzf gh jq \
  lua-language-server node npm npx rg rust-analyzer shellcheck starship \
  treehouse typescript-language-server; do
  printf '#!/usr/bin/env bash\nprintf "%%s\\n" "\xe2\x9d\xaf"\n' > "${PHYN_DEV_NIX_PROFILE:?}/$tool"
  chmod +x "${PHYN_DEV_NIX_PROFILE:?}/$tool"
done
SH
  chmod +x "$hm_out/activate"
  # No curl fixture at all: bootstrap_nix must never be reached.

  export PHYN_DEV_HM_OUT="$hm_out" PHYN_DEV_NIX_LOG="$nix_log" \
    PHYN_DEV_HM_ACTIVATE_LOG="$activate_log" \
    PHYN_DEV_NIX_DAEMON_PROFILE="$case_dir/no-such-daemon-nix" \
    PHYN_DEV_NIX_DAEMON_PROFILE_SCRIPT="$case_dir/no-such-daemon-nix.sh" \
    PHYN_DEV_HM_PROFILE_ROOT="$hm_out/home-files" \
    PHYN_DEV_SKIP_TOOLS=1

  out=$(linux_phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$fakebin" aarch64 \
    "$fixture/phynd-dev" install) || fail "Linux install with pre-existing Nix failed: $out"
  assert_contains "$(cat "$nix_log")" "#homeConfigurations.phynd-dev.activationPackage" \
    "an existing Linux Nix installation should still drive standalone Home Manager activation"
  [ -s "$activate_log" ] || fail "Linux activation should still run with a pre-existing Nix"
  pass "phynd-dev reuses a working existing Nix installation on Linux without bootstrapping"
}

test_linux_nix_install_failure_stops_before_activation() {
  unset_linux_install_test_env
  local case_dir fixture home xdg state npm_prefix fakebin out
  local curl_log nix_log activate_log
  case_dir="$TMP_ROOT/linux-install-failure"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  fakebin="$case_dir/fakebin"
  curl_log="$case_dir/curl.log"
  nix_log="$case_dir/nix-build.log"
  activate_log="$case_dir/activate.log"
  mkdir -p "$home" "$fakebin"
  make_phynd_fixture "$ROOT" "$fixture"
  : > "$curl_log"
  : > "$nix_log"
  : > "$activate_log"

  cat > "$fakebin/curl" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_CURL_LOG:?}"
exit 1
SH
  chmod +x "$fakebin/curl"

  export PHYN_DEV_CURL_LOG="$curl_log" PHYN_DEV_NIX_LOG="$nix_log" \
    PHYN_DEV_HM_ACTIVATE_LOG="$activate_log" \
    PHYN_DEV_NIX_DAEMON_PROFILE="$case_dir/no-such-daemon-nix" \
    PHYN_DEV_NIX_DAEMON_PROFILE_SCRIPT="$case_dir/no-such-daemon-nix.sh" \
    PHYN_DEV_SKIP_TOOLS=1

  if out=$(linux_phynd_env_no_ambient_nix "$home" "$xdg" "$state" "$npm_prefix" "$fakebin" x86_64 \
    "$fixture/phynd-dev" install 2>&1); then
    fail "a failed Nix bootstrap should stop phynd-dev install: $out"
  fi
  assert_contains "$(cat "$curl_log")" "install.determinate.systems/nix" \
    "the failed run should still have attempted the Determinate installer"
  [ ! -s "$nix_log" ] || fail "activation must not be attempted after a failed Nix install"
  [ ! -s "$activate_log" ] || fail "the Home Manager activation script must not run after a failed Nix install"
  pass "phynd-dev reports a failed Linux Nix installation honestly and never reaches activation"
}

test_darwin_flake_check_still_uses_darwin_configurations() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log out
  case_dir="$TMP_ROOT/flake-check-dispatch"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  : > "$nix_log"
  : > "$rebuild_log"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" flake-check) || fail "Darwin flake-check failed: $out"
  assert_contains "$(cat "$nix_log")" "darwin configuration eval" \
    "Darwin flake-check should evaluate darwinConfigurations, not homeConfigurations"
  pass "flake-check keeps evaluating darwinConfigurations.phynd-dev on the Darwin dispatch path"
}

test_linux_flake_check_uses_home_configurations() {
  local case_dir fixture home xdg state npm_prefix fakebin nix_log out
  unset_linux_install_test_env
  case_dir="$TMP_ROOT/linux-flake-check-dispatch"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  fakebin="$case_dir/fakebin"
  nix_log="$case_dir/nix.log"
  mkdir -p "$home" "$fakebin"
  make_phynd_fixture "$ROOT" "$fixture"
  : > "$nix_log"

  cat > "$fakebin/nix" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'nix (fake Linux flake-check)'
  exit 0
fi
if [ "${1:-}" = flake ] && [ "${2:-}" = check ]; then
  exit 0
fi
if [ "${1:-}" = eval ]; then
  printf '%s\n' "$*" >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
exit 0
SH
  chmod +x "$fakebin/nix"
  export PHYN_DEV_NIX_LOG="$nix_log"

  out=$(linux_phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$fakebin" x86_64 \
    "$fixture/phynd-dev" flake-check) || fail "Linux flake-check failed: $out"
  assert_contains "$(cat "$nix_log")" "#homeConfigurations.phynd-dev.activationPackage.drvPath" \
    "Linux flake-check should evaluate homeConfigurations.phynd-dev"
  assert_not_contains "$(cat "$nix_log")" "darwinConfigurations" \
    "Linux flake-check should never evaluate darwinConfigurations"
  pass "flake-check evaluates homeConfigurations.phynd-dev on the Linux dispatch path"
}

test_real_nix_cross_evaluates_linux_home_configuration() {
  local out
  if ! PATH="$REAL_PATH" command -v nix >/dev/null 2>&1; then
    pass "real Nix cross-evaluation of the Linux configuration skipped: no nix on this host"
    return 0
  fi
  # Cross-evaluation from whatever host this runs on (Darwin or Linux): proves
  # the flake's homeConfigurations.phynd-dev output evaluates for a Linux
  # system without building it. This is evaluation evidence, not a native
  # Linux build; native build/activation evidence is out of band (see the
  # task's self-review report for the disposable-container verification).
  out=$(PATH="$REAL_PATH" PHYN_DEV_SYSTEM=x86_64-linux PHYN_DEV_USER=phynd \
    PHYN_DEV_HOME=/home/phynd PHYN_DEV_ROOT="$ROOT" \
    nix eval --no-write-lock-file --impure --raw \
    "$ROOT#homeConfigurations.phynd-dev.activationPackage.drvPath" 2>&1) \
    || fail "real Nix could not cross-evaluate the Linux standalone Home Manager configuration: $out"
  assert_contains "$out" ".drv" \
    "cross-evaluating the Linux configuration should resolve to a derivation path"
  out=$(PATH="$REAL_PATH" PHYN_DEV_SYSTEM=aarch64-linux PHYN_DEV_USER=phynd \
    PHYN_DEV_HOME=/home/phynd PHYN_DEV_ROOT="$ROOT" \
    nix eval --no-write-lock-file --impure --raw \
    "$ROOT#homeConfigurations.phynd-dev.activationPackage.drvPath" 2>&1) \
    || fail "real Nix could not cross-evaluate the aarch64-linux configuration: $out"
  assert_contains "$out" ".drv" \
    "cross-evaluating the aarch64-linux configuration should resolve to a derivation path"
  out=$(PATH="$REAL_PATH" PHYN_DEV_SYSTEM=aarch64-darwin PHYN_DEV_USER=phynd \
    PHYN_DEV_HOME=/Users/phynd PHYN_DEV_ROOT="$ROOT" \
    nix eval --no-write-lock-file --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.system.build.toplevel.drvPath" 2>&1) \
    || fail "real Nix could not still evaluate the preserved Darwin configuration: $out"
  assert_contains "$out" ".drv" \
    "the Darwin configuration should still resolve to a derivation path"
  pass "real Nix evaluates the flake's homeConfigurations.phynd-dev output for both Linux architectures and still evaluates darwinConfigurations.phynd-dev"
}

test_root_entrypoint_resolves_itself
test_npm_tools_ignore_stale_path_commands
test_install_tool_repairs_outdated_no_mistakes
test_install_noop_update_and_safe_backup
test_activation_handles_determinate_custom_conf
test_flake_update_and_check_are_explicit
test_fresh_effective_config_and_wezterm_load
test_repo_starship_config_is_usable
test_starship_is_nix_managed_and_loaded_once
test_host_system_detects_linux_and_refuses_unsupported
test_linux_install_bootstraps_nix_then_activates_home_manager
test_linux_existing_nix_is_reused_without_bootstrapping
test_linux_nix_install_failure_stops_before_activation
test_darwin_flake_check_still_uses_darwin_configurations
test_linux_flake_check_uses_home_configurations
test_real_nix_cross_evaluates_linux_home_configuration
