#!/usr/bin/env bash
# Behavior tests for the isolated phynd-dev lifecycle and repo-owned tools.
set -u

# shellcheck source=tests/lib.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

ROOT=${ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)}
TMP_ROOT=$(fm_test_tmproot phynd-dev-tests)
REAL_PATH=$PATH

make_fake_phynd_tools() {
  local dir=$1 tool
  mkdir -p "$dir"
  cat > "$dir/nix" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'nix (fake phynd-dev test)'
  exit 0
fi
if [ "${1:-}" = flake ] && [ "${2:-}" = update ]; then
  printf '%s\n' 'flake update' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
if [ "${1:-}" = flake ] && [ "${2:-}" = check ]; then
  printf '%s\n' 'flake check' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
if [ "${1:-}" = eval ]; then
  printf '%s\n' 'darwin configuration eval' >> "${PHYN_DEV_NIX_LOG:?}"
  exit 0
fi
exit 0
SH
  cat > "$dir/darwin-rebuild" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_REBUILD_LOG:?}"
mkdir -p "$PHYN_DEV_HOME/.local/bin"
mkdir -p "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager"
mkdir -p "$PHYN_DEV_HOME/.config/zsh"
printf '%s\n' '# generated by the fake Home Manager activation' \
  > "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/zshrc"
ln -sfn "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/zshrc" \
  "$PHYN_DEV_HOME/.config/zsh/.zshrc"
ln -sfn "$PHYN_DEV_ROOT/bin/phynd-dev" \
  "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/phynd-dev"
ln -sfn "$PHYN_DEV_HOME/.local/state/phynd-dev/home-manager/phynd-dev" \
  "$PHYN_DEV_HOME/.local/bin/phynd-dev"
SH
  chmod +x "$dir/nix" "$dir/darwin-rebuild"
  cat > "$dir/brew" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = list ] && [ "${PHYN_TEST_MISSING_BREW_PACKAGE:-}" = "${3:-}" ]; then
  exit 1
fi
exit 0
SH
  chmod +x "$dir/brew"
  for tool in actionlint basedpyright basedpyright-langserver fd fresh fzf gh git jq \
    lua-language-server node npm npx rg rust-analyzer shellcheck starship treehouse \
    typescript-language-server tmux curl; do
    cat > "$dir/$tool" <<'SH'
#!/usr/bin/env bash
printf '%s\n' '❯'
SH
    chmod +x "$dir/$tool"
  done
  PHYN_TEST_NIX_PROFILE=$dir
  PHYN_TEST_SYSTEM_PROFILE=$dir
  PHYN_TEST_GLOBALBIN=
  PHYN_TEST_SKIP_TOOLS=1
  export PHYN_TEST_NIX_PROFILE PHYN_TEST_SYSTEM_PROFILE PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS
}

make_phynd_fixture() {
  local source=$1 fixture=$2
  mkdir -p "$fixture/bin" "$fixture/config/fresh" "$fixture/home/wezterm" "$fixture/nix"
  cp "$source/phynd-dev" "$fixture/phynd-dev"
  cp "$source/bin/phynd-dev" "$fixture/bin/phynd-dev"
  cp "$source/flake.nix" "$fixture/flake.nix"
  cp "$source/flake.lock" "$fixture/flake.lock" 2>/dev/null || : > "$fixture/flake.lock"
  cp "$source/config/fresh/config.json" "$fixture/config/fresh/config.json"
  cp "$source/config/starship.toml" "$fixture/config/starship.toml"
  cp "$source/home/wezterm/wezterm.lua" "$fixture/home/wezterm/wezterm.lua"
  cp "$source/nix/configuration.nix" "$fixture/nix/configuration.nix"
  cp "$source/nix/home.nix" "$fixture/nix/home.nix"
  chmod +x "$fixture/phynd-dev" "$fixture/bin/phynd-dev"
}

phynd_env() {
  local home=$1 xdg=$2 state=$3 npm_prefix=$4 log=$5 rebuild_log=$6 path
  shift 6
  path="$PHYN_TEST_FAKEBIN:$REAL_PATH"
  if [ -n "${PHYN_TEST_GLOBALBIN:-}" ]; then
    path="$PHYN_TEST_FAKEBIN:$PHYN_TEST_GLOBALBIN:$REAL_PATH"
  fi
  HOME="$home" \
  PHYN_DEV_HOME="$home" \
  PHYN_DEV_XDG_CONFIG_HOME="$xdg" \
  PHYN_DEV_STATE_DIR="$state" \
  PHYN_DEV_NPM_PREFIX="$npm_prefix" \
  PHYN_DEV_USER="$(id -un)" \
  PHYN_DEV_SKIP_SUDO=1 \
  PHYN_DEV_SKIP_TOOLS="${PHYN_TEST_SKIP_TOOLS:-1}" \
  PHYN_DEV_UNAME_S=Darwin \
  PHYN_DEV_UNAME_M=arm64 \
  PHYN_DEV_NIX_LOG="$log" \
  PHYN_DEV_REBUILD_LOG="$rebuild_log" \
  PHYN_DEV_NIX_PROFILE="${PHYN_TEST_NIX_PROFILE:-$home/nix-profile/bin}" \
  PHYN_DEV_SYSTEM_PROFILE="${PHYN_TEST_SYSTEM_PROFILE:-/run/current-system/sw/bin}" \
  PHYN_DEV_HM_PROFILE_ROOT="$home/.local/state/phynd-dev/home-manager" \
  PATH="$path" \
  "$@"
}

test_npm_tools_ignore_stale_path_commands() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log npm_log out count
  case_dir="$TMP_ROOT/npm-tools"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/custom-xdg"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  npm_log="$case_dir/npm.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  cat > "$case_dir/fakebin/npm" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$*" >> "${PHYN_DEV_NPM_LOG:?}"
mkdir -p "$NPM_CONFIG_PREFIX/bin"
for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
  cat > "$NPM_CONFIG_PREFIX/bin/$tool" <<'TOOL'
#!/usr/bin/env bash
exit 0
TOOL
  chmod +x "$NPM_CONFIG_PREFIX/bin/$tool"
done
SH
  chmod +x "$case_dir/fakebin/npm"
  mkdir -p "$case_dir/globalbin"
  cat > "$case_dir/globalbin/no-mistakes" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'no-mistakes version v1.46.0 (fake)'
fi
SH
  chmod +x "$case_dir/globalbin/no-mistakes"
  for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
    cat > "$case_dir/globalbin/$tool" <<'SH'
#!/usr/bin/env bash
exit 0
SH
    chmod +x "$case_dir/globalbin/$tool"
  done
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  PHYN_TEST_SKIP_TOOLS=0
  PHYN_DEV_BACKUP_SUFFIX=ghf-test
  PHYN_DEV_NPM_LOG="$npm_log"
  export PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS PHYN_DEV_BACKUP_SUFFIX PHYN_DEV_NPM_LOG
  : > "$nix_log"
  : > "$rebuild_log"
  : > "$npm_log"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "npm-tool reconciliation failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 7 ] || fail "initial install should reconcile each npm tool once"
  rm "$home/.local/bin/ghf"
  printf '%s\n' unrelated > "$home/.local/bin/ghf"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "ghf backup repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 14 ] || fail "an unrelated ghf target should trigger gnhf repair"
  [ "$(cat "$home/.local/bin/ghf.phynd-dev-backup-ghf-test")" = unrelated ] \
    || fail "an unrelated ghf target should be preserved in a backup"
  [ -L "$home/.local/bin/ghf" ] || fail "gnhf repair should restore the managed ghf link"
  rm -f "$home/.local/bin/ghf"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "ghf-link repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 21 ] || fail "missing ghf link should trigger gnhf repair"
  rm "$npm_prefix/bin/"*
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "npm-tool repair failed: $out"
  count=$(wc -l < "$npm_log" | tr -d ' ')
  [ "$count" -eq 28 ] || fail "stale global npm tools should not suppress repair"
  pass "npm-managed tools ignore stale commands outside the managed prefix"
}

test_root_entrypoint_resolves_itself() {
  local case_dir out
  case_dir="$TMP_ROOT/root-entrypoint"
  mkdir -p "$case_dir/home"
  out=$(cd /tmp && HOME="$case_dir/home" PHYN_DEV_UNAME_S=Darwin \
    PHYN_DEV_UNAME_M=arm64 "$ROOT/phynd-dev" status) \
    || fail "root phynd-dev entrypoint should work from another caller directory"
  assert_contains "$out" "checkout: $ROOT" "root entrypoint should identify its own checkout"
  assert_contains "$out" "system:   aarch64-darwin" "root entrypoint should resolve the host system"
  pass "root phynd-dev delegates to bin/phynd-dev independent of caller directory"
}

test_install_tool_repairs_outdated_no_mistakes() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log marker out
  case_dir="$TMP_ROOT/no-mistakes-repair"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  marker="$case_dir/repaired"
  mkdir -p "$home" "$case_dir/globalbin"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  PHYN_TEST_SKIP_TOOLS=1
  PHYN_DEV_NM_MARKER="$marker"
  export PHYN_TEST_FAKEBIN PHYN_TEST_GLOBALBIN PHYN_TEST_SKIP_TOOLS PHYN_DEV_NM_MARKER
  cat > "$case_dir/globalbin/no-mistakes" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = --version ]; then
  printf '%s\n' 'no-mistakes version v1.45.4 (fake)'
fi
SH
  chmod +x "$case_dir/globalbin/no-mistakes"
  cat > "$case_dir/fakebin/curl" <<'SH'
#!/usr/bin/env bash
printf '%s\n' 'printf repaired > "${PHYN_DEV_NM_MARKER:?}"'
SH
  chmod +x "$case_dir/fakebin/curl"
  cat > "$case_dir/fakebin/npm" <<'SH'
#!/usr/bin/env bash
mkdir -p "$NPM_CONFIG_PREFIX/bin"
for tool in pi gnhf gh-axi chrome-devtools-axi lavish-axi tasks-axi quota-axi; do
  printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$NPM_CONFIG_PREFIX/bin/$tool"
  chmod +x "$NPM_CONFIG_PREFIX/bin/$tool"
done
SH
  chmod +x "$case_dir/fakebin/npm"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install-tool no-mistakes) \
    || fail "outdated no-mistakes repair failed: $out"
  [ "$(cat "$marker")" = repaired ] \
    || fail "outdated no-mistakes should run the official installer"
  rm "$marker"
  PHYN_TEST_SKIP_TOOLS=0
  export PHYN_TEST_SKIP_TOOLS
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) \
    || fail "regular install should repair outdated no-mistakes: $out"
  [ "$(cat "$marker")" = repaired ] \
    || fail "regular install should use the no-mistakes version convergence check"
  pass "phynd-dev repairs outdated no-mistakes installations"
}

test_install_noop_update_and_safe_backup() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log system_profile out count
  case_dir="$TMP_ROOT/lifecycle"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/custom-xdg"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home" "$xdg/fresh"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  export PHYN_DEV_BACKUP_SUFFIX=test
  : > "$nix_log"
  : > "$rebuild_log"
  printf '%s\n' '{"captain_private":true}' > "$xdg/fresh/config.json"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install) || fail "initial phynd-dev install failed: $out"
  assert_contains "$out" "activation state recorded" "initial install should record activation"
  [ -L "$xdg/fresh/config.json" ] || fail "Fresh config should be linked after install"
  [ "$(readlink "$xdg/fresh/config.json")" = "$fixture/config/fresh/config.json" ] \
    || fail "Fresh link should target the repository source"
  [ "$(cat "$xdg/fresh/config.json.phynd-dev-backup-test")" = '{"captain_private":true}' ] \
    || fail "existing Fresh configuration should be preserved in a backup"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 1 ] || fail "initial install should activate exactly once"

  out=$(cd /tmp && HOME="$home" PHYN_DEV_HOME="$home" \
    PHYN_DEV_UNAME_S=Darwin PHYN_DEV_UNAME_M=arm64 \
    "$home/.local/bin/phynd-dev" status) \
    || fail "the Home Manager-installed phynd-dev command failed: $out"
  assert_contains "$out" "checkout: $fixture" \
    "the installed phynd-dev command should resolve its repository root"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "second phynd-dev install failed: $out"
  assert_contains "$out" "already converged" "second install should report a no-op"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 1 ] || fail "second install should not reactivate nix-darwin"

  rm "$home/.config/zsh/.zshrc"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Home Manager shell state: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 2 ] || fail "missing Home Manager shell state should trigger activation"

  PHYN_TEST_MISSING_BREW_PACKAGE=herdr
  export PHYN_TEST_MISSING_BREW_PACKAGE
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Homebrew formula state: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 3 ] || fail "missing Homebrew formula should trigger activation"
  unset PHYN_TEST_MISSING_BREW_PACKAGE

  system_profile="$case_dir/system-profile"
  mkdir -p "$system_profile"
  cp "$case_dir/fakebin/fresh" "$system_profile/fresh"
  PHYN_TEST_SYSTEM_PROFILE="$system_profile"
  export PHYN_TEST_SYSTEM_PROFILE
  rm "$case_dir/fakebin/fresh"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair a Home Manager package shadowed by system PATH: $out"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 4 ] || fail "a stale system package should not suppress Home Manager repair"
  cp "$system_profile/fresh" "$case_dir/fakebin/fresh"
  chmod +x "$case_dir/fakebin/fresh"

  mkdir -p "$case_dir/globalbin"
  cp "$case_dir/fakebin/starship" "$case_dir/globalbin/starship"
  chmod +x "$case_dir/globalbin/starship"
  rm "$case_dir/fakebin/starship"
  PHYN_TEST_GLOBALBIN="$case_dir/globalbin"
  export PHYN_TEST_GLOBALBIN
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" install) \
    || fail "phynd-dev should repair missing Nix-managed packages: $out"
  assert_contains "$out" "applying pinned nix-darwin" \
    "a missing managed package should invalidate the activation no-op"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 5 ] || fail "missing managed package should trigger one reactivation"
  cat > "$case_dir/fakebin/starship" <<'SH'
#!/usr/bin/env bash
printf '%s\n' '❯'
SH
  chmod +x "$case_dir/fakebin/starship"

  printf '\n# later repo configuration revision\n' >> "$fixture/config/starship.toml"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" \
    "$nix_log" "$rebuild_log" "$fixture/phynd-dev" update) \
    || fail "phynd-dev update failed: $out"
  assert_contains "$out" "applying pinned nix-darwin" "changed configuration should reactivate"
  count=$(wc -l < "$rebuild_log" | tr -d ' ')
  [ "$count" -eq 6 ] || fail "updated configuration should activate once more"
  pass "phynd-dev install, converged no-op, update, and safe backup paths are idempotent"
}

test_flake_update_and_check_are_explicit() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log out
  case_dir="$TMP_ROOT/flake-actions"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  : > "$nix_log"
  : > "$rebuild_log"

  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" flake-check) || fail "flake-check path failed: $out"
  assert_contains "$out" "evaluating the pinned flake" "flake-check should explain its action"
  out=$(phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" flake-update) || fail "flake-update path failed: $out"
  assert_contains "$out" "updating the flake lock" "flake-update should explain its action"
  assert_contains "$(cat "$nix_log")" "flake check" "flake-check should invoke nix"
  assert_contains "$(cat "$nix_log")" "darwin configuration eval" \
    "flake-check should evaluate the Darwin configuration"
  assert_contains "$(cat "$nix_log")" "flake update" "flake-update should invoke nix"
  if [ "$(uname -s)" = Darwin ] && PATH="$REAL_PATH" command -v nix >/dev/null 2>&1; then
    out=$(PATH="$REAL_PATH" nix flake check --no-build --impure "$fixture") \
      || fail "real Nix could not evaluate the pinned fixture flake: $out"
    out=$(PATH="$REAL_PATH" nix eval --no-write-lock-file --impure --raw \
      "$fixture#darwinConfigurations.phynd-dev.config.system.build.toplevel.drvPath") \
      || fail "real Nix could not evaluate the Darwin/Home Manager configuration: $out"
    pass "real Nix evaluates the flake and Darwin configuration without building closures"
  else
    pass "real Nix evaluation skipped because this host lacks Darwin Nix"
  fi
  pass "flake-check and flake-update remain explicit, separate lifecycle paths"
}

test_fresh_effective_config_and_wezterm_load() {
  local case_dir fixture home xdg state npm_prefix nix_log rebuild_log show out lsp_path
  case_dir="$TMP_ROOT/editor-config"
  fixture="$case_dir/repo"
  home="$case_dir/home"
  xdg="$home/.config"
  state="$home/.local/state/phynd-dev"
  npm_prefix="$home/.local/share/phynd-dev/npm"
  nix_log="$case_dir/nix.log"
  rebuild_log="$case_dir/rebuild.log"
  mkdir -p "$home"
  make_phynd_fixture "$ROOT" "$fixture"
  make_fake_phynd_tools "$case_dir/fakebin"
  PHYN_TEST_FAKEBIN="$case_dir/fakebin"
  export PHYN_TEST_FAKEBIN
  : > "$nix_log"
  : > "$rebuild_log"
  phynd_env "$home" "$xdg" "$state" "$npm_prefix" "$nix_log" "$rebuild_log" \
    "$fixture/phynd-dev" install >/dev/null \
    || fail "editor-config install failed"

  if [ "$(uname -s)" = Darwin ]; then
    command -v fresh >/dev/null 2>&1 \
      || fail "Fresh is required on the supported Darwin path"
    show=$(HOME="$home" XDG_CONFIG_HOME="$xdg" PATH="$REAL_PATH" \
      fresh --cmd config show) || fail "Fresh could not load the activated repo config"
    printf '%s\n' "$show" | jq -e '
      .file_explorer.show_gitignored == true and
      .file_explorer.respect_gitignore == true and
      .lsp.typescript[0].command == "typescript-language-server" and
      .lsp.typescript[0].auto_start == true and
      .lsp.javascript[0].command == "typescript-language-server" and
      .lsp.rust[0].command == "rust-analyzer" and
      .lsp.lua[0].command == "lua-language-server" and
      .lsp.python[0].command == "basedpyright-langserver" and
      (.lsp.typescript[0].root_markers | index(".git")) != null and
      (.lsp.rust[0].root_markers | index("Cargo.toml")) != null and
      (.lsp.python[0].root_markers | index("pyproject.toml")) != null
    ' >/dev/null || fail "Fresh effective config did not expose the managed explorer and LSP settings"
    lsp_path="$case_dir/lsp-bin"
    mkdir -p "$lsp_path"
    for tool in typescript-language-server rust-analyzer lua-language-server basedpyright-langserver; do
      cat > "$lsp_path/$tool" <<'SH'
#!/usr/bin/env bash
printf '%s\n' "$(basename "$0")" >> "${FRESH_LSP_LOG:?}"
while IFS= read -r line; do
  :
done
SH
      chmod +x "$lsp_path/$tool"
    done
    for language in typescript javascript rust lua python; do
      workspace="$case_dir/workspace/apps/$language/src"
      mkdir -p "$workspace"
      case "$language" in
        typescript) file="$workspace/main.ts" ;;
        javascript) file="$workspace/main.js" ;;
        rust) file="$workspace/main.rs" ;;
        lua) file="$workspace/main.lua" ;;
        python) file="$workspace/main.py" ;;
      esac
      printf '%s\n' invalid > "$file"
      session="phynd-$language"
      lsp_log="$case_dir/$language-lsp.log"
      : > "$lsp_log"
      out=$(HOME="$home" XDG_CONFIG_HOME="$xdg" \
        FRESH_LSP_LOG="$lsp_log" \
        PATH="$lsp_path:$REAL_PATH" \
        fresh --no-upgrade-check --cmd daemon open-file "$session" "$file" 2>&1) \
        || fail "Fresh could not attach the isolated $language workspace: $out"
      assert_contains "$out" "opened 1 file(s)" \
        "Fresh should attach the isolated $language workspace through its daemon"
      attempts=0
      while [ ! -s "$lsp_log" ] && [ "$attempts" -lt 20 ]; do
        sleep 0.1
        attempts=$((attempts + 1))
      done
      [ -s "$lsp_log" ] \
        || fail "Fresh did not start the configured $language language server"
      HOME="$home" XDG_CONFIG_HOME="$xdg" \
        PATH="$lsp_path:$REAL_PATH" \
        fresh --no-upgrade-check --cmd daemon kill "$session" >/dev/null 2>&1 || :
    done
    pass "Fresh loads managed settings and starts servers for all five languages"
  else
    pass "Fresh executable validation skipped outside the supported Darwin host"
  fi

  if command -v wezterm >/dev/null 2>&1; then
    out=$(HOME="$home" XDG_CONFIG_HOME="$xdg" PATH="$REAL_PATH" \
      wezterm show-keys --lua 2>&1) || fail "WezTerm could not load the activated repo Lua config: $out"
    pass "WezTerm's config-loading surface accepts the activated repo-owned Lua source"
  else
    pass "WezTerm config-loading validation skipped because WezTerm is not installed in this test environment"
  fi
}

test_repo_starship_config_is_usable() {
  local out
  if command -v starship >/dev/null 2>&1; then
    out=$(starship --config "$ROOT/config/starship.toml" prompt 2>&1) \
      || fail "Starship could not render the repo-owned configuration: $out"
    [ -n "$out" ] || fail "Starship rendered an empty prompt from the repo-owned configuration"
    pass "Starship renders a prompt from the repo-owned configuration"
  else
    pass "Starship prompt validation skipped because Starship is not installed in this test environment"
  fi
}

test_starship_is_nix_managed_and_loaded_once() {
  local shell_home zsh_dir zshrc zshenv zprofile zlogin enabled out call_log
  if [ "$(uname -s)" != Darwin ] || ! command -v nix >/dev/null 2>&1 || \
    ! command -v zsh >/dev/null 2>&1; then
    pass "Starship Nix activation validation skipped outside a Darwin host with Nix"
    return 0
  fi
  shell_home="$TMP_ROOT/starship-shell-home"
  mkdir -p "$shell_home/bin"
  printf '%s\n' 'export PHYN_EXISTING_ENV=preserved' > "$shell_home/.zshenv"
  printf '%s\n' 'export PHYN_EXISTING_PROFILE=preserved' > "$shell_home/.zprofile"
  printf '%s\n' 'export PHYN_EXISTING_LOGIN=preserved' > "$shell_home/.zlogin"
  printf '%s\n' 'eval "$(starship init zsh)"' > "$shell_home/.zshrc"
  call_log="$shell_home/starship-calls.log"
  cat > "$shell_home/bin/starship" <<'SH'
#!/usr/bin/env bash
if [ "${1:-}" = init ] && [ "${2:-}" = zsh ]; then
  printf '%s\n' init >> "${STARSHIP_CALL_LOG:?}"
  printf '%s\n' 'PROMPT="❯ "'
fi
SH
  chmod +x "$shell_home/bin/starship"
  enabled=$(nix eval --impure --json \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.programs.starship.enableZshIntegration") \
    || fail "Nix could not evaluate the generated Starship zsh integration setting"
  [ "$enabled" = true ] || fail "Home Manager should own Starship's zsh integration"
  zshrc=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zshrc\".text") \
    || fail "Nix could not evaluate the generated interactive zsh configuration"
  zshenv=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zshenv\".text") \
    || fail "Nix could not evaluate the generated zshenv configuration"
  zprofile=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zprofile\".text") \
    || fail "Nix could not evaluate the generated zprofile configuration"
  zlogin=$(PHYN_DEV_HOME="$shell_home" \
    nix eval --impure --raw \
    "$ROOT#darwinConfigurations.phynd-dev.config.home-manager.users.phynd.home.file.\".config/zsh/.zlogin\".text") \
    || fail "Nix could not evaluate the generated zlogin configuration"
  zsh_dir="$shell_home/.config/zsh"
  mkdir -p "$zsh_dir"
  printf '%s\n' "$zshenv" > "$zsh_dir/.zshenv"
  printf '%s\n' "$zprofile" > "$zsh_dir/.zprofile"
  printf '%s\n' "$zshrc" > "$zsh_dir/.zshrc"
  printf '%s\n' "$zlogin" > "$zsh_dir/.zlogin"
  out=$(HOME="$shell_home" ZDOTDIR="$zsh_dir" TERM=xterm \
    STARSHIP_CALL_LOG="$call_log" PATH="$shell_home/bin:$PATH" \
    zsh -ilc 'printf "%s\\n" "$PHYN_EXISTING_ENV" "$PHYN_EXISTING_PROFILE" "$PHYN_EXISTING_LOGIN"; print -P -- "$PROMPT"' 2>&1) \
    || fail "a fresh interactive zsh could not load the generated configuration: $out"
  assert_contains "$out" "preserved" \
    "a fresh interactive zsh should preserve all conventional user startup files"
  assert_contains "$out" "❯" \
    "a fresh interactive zsh should render the repo-owned Starship prompt"
  [ "$(wc -l < "$call_log" | tr -d ' ')" -eq 1 ] \
    || fail "a fresh interactive zsh should initialize Starship exactly once"
  pass "Nix-managed Starship renders through the generated interactive zsh configuration"
}

test_root_entrypoint_resolves_itself
test_npm_tools_ignore_stale_path_commands
test_install_tool_repairs_outdated_no_mistakes
test_install_noop_update_and_safe_backup
test_flake_update_and_check_are_explicit
test_fresh_effective_config_and_wezterm_load
test_repo_starship_config_is_usable
test_starship_is_nix_managed_and_loaded_once
